### ISSUE TITLE
Restore tests for image signature workflow

### ISSUE THREAD

**Issue by dmage** [openshift/image-registry#39]
https://github.com/openshift/origin/commit/4e138933d41d0d31cad139f6687e3951df1345a6#diff-d1daafcc0a0ef1e009d0dd44848d8ac4

**Comment by miminar** [comment]
Copy&paste from the closed duplicate #74:

Was openshift/origin#16344

The test existed in the origin repository: https://github.com/miminar/origin/blob/262b8bafff6b5f338e647c94bc9530121fc18131/test/extended/registry/signature.go

It was re-enabled in openshift/origin#17202 and removed one week later during a rebase to kube 1.8.1 (openshift/origin#17115) since it allegedly belongs to this repository.
