### ISSUE TITLE
Get blob may return 200/206 when blob is not present on storage

### ISSUE THREAD

**Issue by dmage** [openshift/image-registry#70]
> 10.128.0.1 - - [19/Feb/2018:07:45:44 +0000] "GET /v2/extended-test-prune-images-xkcfs-7jg44/origin-release/blobs/sha256:ae60289ae57f6a7da4a23756109b6078c209a2e280be031a70bf00e198b6b1a0 HTTP/2.0" 206 2 "" "Go-http-client/2.0"

> 10.128.0.1 - - [19/Feb/2018:07:45:51 +0000] "DELETE /v2/extended-test-prune-images-xkcfs-7jg44/origin-release/blobs/sha256:ae60289ae57f6a7da4a23756109b6078c209a2e280be031a70bf00e198b6b1a0 HTTP/2.0" 202 0 "" "oc/v1.9.1+a0ce1bc657 (linux/amd64) kubernetes/a0ce1bc"

> 10.128.0.1 - - [19/Feb/2018:07:45:53 +0000] "DELETE /admin/blobs/sha256:ae60289ae57f6a7da4a23756109b6078c209a2e280be031a70bf00e198b6b1a0 HTTP/2.0" 204 0 "" "oc/v1.9.1+a0ce1bc657 (linux/amd64) kubernetes/a0ce1bc"

> 10.128.0.1 - - [19/Feb/2018:07:47:13 +0000] "GET /v2/extended-test-prune-images-xkcfs-rqqql/origin-release/blobs/sha256:ae60289ae57f6a7da4a23756109b6078c209a2e280be031a70bf00e198b6b1a0 HTTP/2.0" 206 0 "" "Go-http-client/2.0"

**Comment by dmage** [comment]
https://github.com/docker/distribution/blob/master/ROADMAP.md#deletes

**Comment by dmage** [comment]
https://github.com/docker/distribution/blob/6664ec703991875e14419ff4960921cce7678bab/registry/storage/filereader.go#L125-L130

**Comment by bparees** [comment]
some context from IRC discussion:

This can happen under the following conditions:

1) you have multiple registry instances
2) an image gets deleted/pruned from storage
3) the cache in the other instances is now stale (containers a blobid that does not exist in storage)
4) docker attempts to fetch a non-existent file from storage, but returns a 200 when the file is not found: https://github.com/docker/distribution/blob/6664ec703991875e14419ff4960921cce7678bab/registry/storage/filereader.go#L125-L130 

The standard docker registry doesn't have a problem w/ this because they do not support deleting blobs out of storage (at least not without restarting the registry instance, which clears the cache).  Using a shared cache would also address it.

@dmage @legionus can you explain why docker would reject a patch that returned a proper error on path not found?  Why do they need to return the empty reader?

**Comment by dmage** [comment]
@bparees https://github.com/docker/distribution/blob/0270bec91642bd3bf61afd05e510526b98b57706/storage/filereader.go#L53-L58

> The only correct behavior is to return a reader that immediately returns EOF.

This was explicitly said in the code.

**Comment by dmage** [comment]
I've made some research to find out why they do it.

On 19 Dec 2014 they made the commit https://github.com/docker/distribution/commit/8ca960a0b57c7e25bf5ebbf4ac13c8aedf8c23de that "requires some discussion of how we will handle errors due to network problems". This change suppress the InvalidRange error, and it's for Distribution v2.0. Though, this code returns PathNotFoundError if the blob is absent on the storage.

On 2 Feb 2015 they started to "handle empty blob files more appropriately", https://github.com/docker/distribution/commit/0270bec91642bd3bf61afd05e510526b98b57706.

> The fileReader has been modified to be more robust when reading and seeking on zero-length or non-existent files. The file no longer needs to exist for the reader to be created.

Their [newFileWriter](https://github.com/docker/distribution/blob/0270bec91642bd3bf61afd05e510526b98b57706/storage/filewriter.go#L38) didn't create anything if nothing was written to the file. To fix it, they made workaround for it.

In theory it can be changed, but in practice we'll need to carefully test it on all supported types of storage, which doesn't seem to be feasible. But the upstream don't have such problems, they don't delete anything and Stat calls fix all their problems. So it won't give them any benefits. On the other hand, we'll need to convince the upstream that our patch is needed and is safe to apply.
